# This is a TOML document. Boom~

jwt_secret = "SX20K1YQ7FT1S3AL4HL5SNV2P6SNF3K2WE8HVK9SN5AWNV"
pwd_md5_secret = "SF24SKG9ZYLQ20Q7FT18VVAP82O2INXLXTHDFI5S8G5NZN"

super_admin_password = "111111"
super_admin_account = "admin"
super_admin_phone = "15365136393"
default_password = "111111"
